@startuml

class Client {
}

class Project {}

class Task {}

class Component {}

class Interval {}

Interface Visitor {
+ visitTask()
+ visitProject()
}

interface Observer {}

abstract class Observable {}

class Clock {}

class Printer {
+ visitTask()
+ visitProject()
}

Client o-down->"n" Component
Project -up-|> Component
Component "n"<-down-o Project
Task -up-|> Component
Task -[hidden]right- Project
Interval "n" -right-* Task
Clock --|> Observable
Printer -up-|> Visitor
Interval -up-|> Observer
Observable *-->"n" Observer

@enduml